apiVersion: v1
kind: Service
metadata:
  name: kuber-test-service
spec:
  selector:
    app: kuber-test
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  spec:
    type: ExternalName
    externalName: ip172-18-0-17-ci4a63g14qbg00epbbcg.direct.labs.play-with-k8s.com